name: "Feature request"
description: "Suggest a new feature or enhancement. Use English only and search existing issues first."
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Important:** This issue must be written in English. Issues in other languages will be closed.
        Please search existing open and closed issues before creating a new one to avoid duplicates.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your feature request
      options:
        - label: I have searched existing open and closed issues for duplicates
          required: true
        - label: I am writing this issue in English
          required: true
        - label: I have read the documentation in the README
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you would like to see added
      placeholder: Describe the feature you'd like to see implemented
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe what problem this feature would solve
      placeholder: I'm always frustrated when... / This would help with...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: What should the feature do and how should it work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: Are there other ways to solve this problem or implement this feature?

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New PDF processing tool
        - Enhancement to existing tool
        - Configuration/Settings improvement
        - Documentation improvement
        - Performance improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific use case or scenario where this feature would be helpful
      placeholder: When would you use this feature? How would it fit into your workflow?
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples about the feature request here
      placeholder: Any additional information that might help us understand your request

  - type: checkboxes
    id: final-check
    attributes:
      label: Final Check
      description: Please confirm before submitting
      options:
        - label: I confirm this issue is written in English and follows the template
          required: true