name: "Feature request"
description: "Suggest a new feature or enhancement. Use English only and search existing issues first."
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Important:** This issue must be written in English. Issues in other languages will be closed.
        Please search existing open and closed issues before creating a new one to avoid duplicates.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your feature request
      options:
        - label: I have searched existing open and closed issues for duplicates
          required: true
        - label: I am writing this issue in English
          required: true
        - label: I have read the documentation in the README
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you would like to see added
      placeholder: Describe the feature you'd like to see implemented
    validations:
      required: true