name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Run ruff check
        run: uvx ruff check .

      - name: Run ruff format check
        run: uvx ruff format --check .

      - name: Run mdformat check
        run: uvx mdformat --check --number .
